dependencies:
- name: bdd-gh-1554101389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1554101389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-ph-1554101389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-rq-1554101389
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
